name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.nix"
      - ".github/workflows/ci.yaml"
  pull_request:
    paths:
      - "**.nix"
      - ".github/workflows/ci.yaml"
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build
        run: |
          nix-build release.nix -A ${{ matrix.system }}
