name: Update flake.lock

on:
  schedule:
    # run every saturday
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  update:
    name: Update

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Update flake.lock & make PR
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          commit-msg: "chore: update flake.lock"
          pr-title: "chore: update flake.lock"
          token: ${{ github.token }}
